accounts/urls.py
from django.urls import path
from django.contrib.auth import views

from .views import SignupView

app_name = "accounts"

urlpatterns = [
    path('login/', views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    # path('logout/', views.LogoutView.as_view(template_name='accounts/logged_out.html'), name='logout'),
    path('signup/', SignupView.as_view(template_name="accounts/signup.html"),
         name="signup"),
]

softdesk/urls.py
from django.contrib import admin
from django.urls import path, include
from rest_framework_nested import routers
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView

from projects.views import ProjectViewset, ContributorViewset, IssueViewset, CommentViewset
from accounts.views import redirection_view

router = routers.SimpleRouter()
router.register(r"projects", ProjectViewset, basename="projects")

projects_router = routers.NestedSimpleRouter(router, r"projects", lookup="project")
projects_router.register(r"users", ContributorViewset, basename="users")

issues_router = routers.NestedSimpleRouter(router, r"projects", lookup="project")
issues_router.register(r"issues", IssueViewset, basename="issues")

comments_router = routers.NestedSimpleRouter(issues_router, r"issues", lookup="issue")
comments_router.register(r"comments", CommentViewset, basename="comments")

urlpatterns = [
    path('', redirection_view, name="index_redirection"),
    path('api/', include("accounts.urls")),
    path('api/admin/', admin.site.urls),
    path('api/', include('rest_framework.urls')),
    path('api/token/', TokenObtainPairView.as_view(), name="token_obtain_pair"),
    path('api/token/refresh/', TokenRefreshView.as_view(), name="token_refresh"),
    path('api/', include(router.urls)),
    path('api/', include(projects_router.urls)),
    path('api/', include(issues_router.urls)),
    path('api/', include(comments_router.urls)),
]

accounts/models.py
from django.db import models, transaction
from django.contrib.auth.base_user import BaseUserManager
from django.contrib.auth.models import AbstractUser


# Create your models here.
class UserManager(BaseUserManager):
    def _create_user(self, email, password, **extra_fields):
        """
        Creates and saves a user with the given email and password
        """
        if not email:
            raise ValueError("Merci de renseigner une adresse email.")
        try:
            with transaction.atomic():
                user = self.model(email=email, **extra_fields)
                user.username = user.email
                user.set_password(password)
                user.save(using=self._db)
                return user
        except (ValueError, AttributeError):
            raise

    def create_user(self, email, password=None, **extra_fields):
        extra_fields.setdefault("is_staff", False)
        extra_fields.setdefault("is_superuser", False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        extra_fields.setdefault("is_staff", True)
        extra_fields.setdefault("is_superuser", True)
        return self._create_user(email, password, **extra_fields)


class CustomUser(AbstractUser):
    """
    A model that represents a user with admin-compliant permissions
    """
    first_name = models.CharField(max_length=20)
    last_name = models.CharField(max_length=20)
    email = models.EmailField(unique=True)
    password = models.CharField(max_length=12, null=False, blank=False)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)

    objects = UserManager()

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = ["first_name", "last_name"]

    def __str__(self):
        return f"{self.first_name} {self.last_name}"


class Contributor(models.Model):
    """
    A model that represents a contributor to a project
    """
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    project = models.ForeignKey("projects.Project", on_delete=models.CASCADE)
    permission = models.CharField(max_length=20, choices=(), null=True)
    role = models.CharField(max_length=20, null=True)

    class Meta:
        constraints = [models.UniqueConstraint(fields=["user", "project"],
                                               name="unique-contributor")]

    def __str__(self):
        return self.user

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.utils.translation import gettext_lazy as _

from .models import CustomUser


class SignupForm(UserCreationForm):
    """
    A custom UserCreationForm for new users to fill in to be able to sign up
    to the application.
    """
    first_name = forms.CharField(max_length=20,
                                 required=False,
                                 label="Prénom")
    last_name = forms.CharField(max_length=20,
                                required=False,
                                label="Nom")
    email = forms.EmailField(error_messages={'unique': "Cet email est déjà utilisé."})
    password1 = forms.CharField(label=_("Mot de passe"))
    password2 = forms.CharField(label=_("Confirmation du mot de passe"))
    error_messages = {
        'password_mismatch': _('Les mots de passe ne sont pas les mêmes.')
    }

    class Meta:
        model = CustomUser
        fields = ["first_name", "last_name", "email", "password1", "password2"]

    def clean(self):
        """
        A method overriding the default BaseForm clean() method to check that
        password and confirmed password match.
        """
        cleaned_data = super(SignupForm, self).clean()
        password1 = cleaned_data.get("password1")
        password2 = cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Le mot de passe doit être identique.")
        return cleaned_data

    def is_valid(self):
        """
        A method overriding the default BaseForm is_valid() method.
        """
        valid = super(SignupForm, self).is_valid()
        if valid:
            return True
        else:
            return False

accounts/views.py
from django.contrib.auth import views
from django.shortcuts import redirect, render

from .forms import SignupForm
from .models import CustomUser


# Create your views here.
def redirection_view(request):
    """
    A FBV (Function-Based View) redirecting index page to the login page.
    """
    return redirect("/api/login/")


class SignupView(views.FormView):
    """
    A custom FormView for new users to sign up to the application.
    """
    form_class = SignupForm

    def get_context_data(self, **kwargs):
        """
        A method overriding the default FormView context data.
        """
        form = SignupForm
        context = {"form": form, "next": "/api/projects/"}
        return context

    def post(self, request, *args, **kwargs):
        """
        A method overriding the default FormView post() method.
        """
        form = SignupForm(request.POST)
        if form.is_valid():
            password = request.POST.get("password1")
            user = CustomUser.objects.create(first_name=request.POST.get("first_name"),
                                             last_name=request.POST.get("last_name"),
                                             email=request.POST.get("email"),
                                             username=request.POST.get("email"),
                                             password=password
                                             )
            user.set_password(password)
            user.save()
            return redirect("projects-list")
        else:
            context = {"form": form}
            return render(request, "accounts/signup.html", context)

accounts/templates/accounts/logged_out.html
{% extends "rest_framework/base.html" %}
{% load rest_framework %}

{% block body %}
<body class="container">
  <div class="container-fluid" style="margin-top: 30px">
    <div class="row-fluid">
      <div class="well" style="width: 620px; margin-left: auto; margin-right: auto">
        <div class="row-fluid">
          <div>
            {% block branding %}<h3 style="margin: 0 0 20px;">Vous avez été déconnecté.</h3>{% endblock %}
          </div>
        </div><!-- /row fluid -->

        <p>Vous pouvez vous reconnecter en cliquant sur le lien ci-dessous:</p>

        <p><a href="{% url 'accounts:login' %}">Se reconnecter</a></p>


      </div><!--/.well-->
    </div><!-- /.row-fluid -->
  </div><!-- /.container-fluid -->
</body>
{% endblock %}

accounts/templates/accounts/login.html
{% extends "rest_framework/base.html" %}
{% load rest_framework %}

{% block body %}
<body class="container">
  <div class="container-fluid" style="margin-top: 30px">
    <div class="row-fluid">
      <div class="well" style="width: 520px; margin-left: auto; margin-right: auto">
        <div class="row-fluid">
          <div>
            {% block branding %}<h3 style="margin: 0 0 20px;">Identifiez-vous sur l'API SoftDesk</h3>{% endblock %}
          </div>
        </div><!-- /row fluid -->

        <div class="row-fluid">
          <div>
            <form action="{% url 'accounts:login' %}" role="form" method="post">
              {% csrf_token %}
              <input type="hidden" name="next" value="{{ next }}" />

              <div id="div_id_username" class="clearfix control-group {% if form.username.errors %}error{% endif %}">
                <div class="form-group">
                  <label for="id_username">{{ form.username.label }}:</label>
                  <input type="text" name="username" maxlength="100"
                      autocapitalize="off"
                      autocorrect="off" class="form-control textinput textInput"
                      id="id_username" required autofocus
                      {% if form.username.value %}value="{{ form.username.value }}"{% endif %}>
                  {% if form.username.errors %}
                    <p class="text-error">
                      {{ form.username.errors|striptags }}
                    </p>
                  {% endif %}
                </div>
              </div>

              <div id="div_id_password" class="clearfix control-group {% if form.password.errors %}error{% endif %}">
                <div class="form-group">
                  <label for="id_password">{{ form.password.label }}:</label>
                  <input type="password" name="password" maxlength="100" autocapitalize="off" autocorrect="off" class="form-control textinput textInput" id="id_password" required>
                  {% if form.password.errors %}
                    <p class="text-error">
                      {{ form.password.errors|striptags }}
                    </p>
                  {% endif %}
                </div>
              </div>

              {% if form.non_field_errors %}
                {% for error in form.non_field_errors %}
                  <div class="well well-small text-error" style="border: none">{{ error }}</div>
                {% endfor %}
              {% endif %}

              <div class="form-actions-no-box">
                <input type="submit" name="submit" value="Log in" class="btn btn-primary form-control" id="submit-id-submit">
              </div>
              <br>
              <div class="form-actions-no-box">
                <a href={% url 'accounts:signup' %}>
                  <p class="btn btn-primary form-control" style="width: 90%";>Sign In</p>
                </a>
              </div>
            </form>
          </div>
        </div><!-- /.row-fluid -->
      </div><!--/.well-->
    </div><!-- /.row-fluid -->
  </div><!-- /.container-fluid -->
</body>
{% endblock %}

accounts/templates/accounts/signup.html
{% extends "rest_framework/base.html" %}
{% load rest_framework %}

{% block body %}
<body class="container">
  <div class="container-fluid" style="margin-top: 30px">
    <div class="row-fluid">
      <div class="well" style="width: 620px; margin-left: auto; margin-right: auto">
        <div class="row-fluid">
          <div>
            {% block branding %}<h3 style="margin: 0 0 20px;">Inscrivez-vous sur l'API SoftDesk</h3>{% endblock %}
          </div>
        </div><!-- /row fluid -->

        <div class="row-fluid">
          <div>
            <form action="" role="form" method="post">
              {% csrf_token %}
              <input type="hidden" name="next" value="{{ next }}" />

              {% for field in form %}
              <div id="" class="clearfix control-group {% if field.errors %}error{% endif %}">
                <div class="form-group">
                  <label for="id_{{ field.name }}">{{ field.label }}:</label>
                  <input type="text" name="{{ field.name}}" maxlength="100"
                      autocapitalize="off"
                      autocorrect="off" class="form-control textinput textInput"
                      id="id_{{ field.name }}" required autofocus
                      {% if field.value %}value="{{ field.value }}"{% endif %}>
                  {% if field.errors %}
                    <p class="text-error" style="color: red; margin-top: .5rem;">
                      {{ field.errors|striptags }}
                    </p>
                  {% endif %}
                </div>
              </div>
              {% endfor %}

<!--              {% if form.non_field_errors %}-->
<!--                {% for error in form.non_field_errors %}-->
<!--                  <div class="well well-small text-error" style="border: none">{{ error }}</div>-->
<!--                {% endfor %}-->
<!--              {% endif %}-->

              <div class="form-actions-no-box">
                <input type="submit" name="submit" value="S'inscrire" class="btn btn-primary form-control" id="submit-id-submit">
              </div>
            </form>
          </div>
        </div><!-- /.row-fluid -->
      </div><!--/.well-->
    </div><!-- /.row-fluid -->
  </div><!-- /.container-fluid -->
</body>
{% endblock %}